name: 'Nasher4GH'
branding:
  icon: 'eye'
  color: 'blue'
author: Mark Collin
description: "Github action that utilises Nasher to build NWN modules"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ardesco/nasher4gh-images:latest'
  args:
    - pack
    - --default
